services:
  # Base de données pour Strapi
  strapi-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Backend Strapi
  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    volumes:
      - ./api:/opt/app
      - /opt/app/node_modules
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi-db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: password
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db

  # Frontend Nuxt
  app:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    volumes:
      - ./app:/src
      - /src/.nuxt
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_STRAPI_URL=http://localhost:1337
    depends_on:
      - api

volumes:
  strapi-data: